### ISSUE TITLE
Properties as Optionals

### ISSUE THREAD

**Issue by Burtan** [sharpmind-de/ktor-env-config#2]
Hi,

Properties are Optionals by default. I wonder why you made this design decision. As far as I can tell, you never want it to be null anyway and if so, it is a bug which could as well throw an error instead of returning null. Currently it leads to the usage of ugly "!!" to force non-null.

Maybe add getNullableString etc. and make the default functions non-null?

**Comment by stolzem** [comment]
Hey, thanks so much for the feedback!
Right, we have been lazy recently to push updated versions. Did this just now, version 1.1.4 is now up.

As you suggested we added 3 different kinds of access methods now:

getXXX()- not nullable, throws exception in case key is missing
getXXXOrNull() - nullable
getXXXOrDefault() - not null, returns default in case key is missing

More details in the Readme file.

Hope that is more useful.

Cheers

**Comment by Burtan** [comment]
Cool! Thanks for the fast update and this nice library. It feels to should be shipped with ktor on default!
