### ISSUE TITLE
Ktor 2 support

### ISSUE THREAD

**Issue by Olaren15** [sharpmind-de/ktor-env-config#4]
Hello I made changes to the code so that it supports Ktor 2

Feel free to integrate it in your project if you like.

here is the repo: https://github.com/Olaren15/ktor2-env-config

**Comment by stolzem** [comment]
Thanks a bunch for your contribution!
Good point in supporting ktor2. Probably going to maintain a ktor2 branch - where we'll pull in your changes.

**Comment by brunapereira** [comment]
Hey! Any updates on that?

**Comment by stolzem** [comment]
So, I released version 2.0.1 which has ktor2 support.
https://search.maven.org/artifact/de.sharpmind.ktor/ktor-env-config/2.0.1/jar

Currently we just have a single ktor2 project, where the lib works fine. But give it a go with your projects and let us know in case of probs.

Cheers.
