### ISSUE TITLE
How can I get env?

### ISSUE THREAD

**Issue by sh-cho** [sharpmind-de/ktor-env-config#5]
```
# application.conf

envConfig {
    env = local
    env = ${?ENVIRONMENT}

    local {
        # ...
    }

    prod {
        # ...
    }
}
```
For instance, I want to execute some code only if `envConfig.env == "local"`.

```kotlin
// Application.kt

fun Application.module() {
    val config = environment.config
    EnvConfig.initConfig(config)
    val isLocal = config.property("envConfig.env").getString() == "local"

    // ...

    if (isLocal) {
        transaction {
            SchemaUtils.create(SomeTable)
            SchemaUtils.create(OtherTable)
        }
    }
}
```
Is this the best approach?

I'm new to Ktor and any advice would be appreciated! :)

**Comment by brunapereira** [comment]
If you're using EnvConfig, you could just use it to get the current env. 

```
val env = EnvConfig.getString("env")

if (env == "production") {
  println("this is prod env")
}
```

**Comment by stolzem** [comment]
As brunapereira pointed out, you get the environment string like this`EnvConfig.getString("env")`

In general you should try to avoid relying on the environment string. In the end these are just arbitrary strings. You don't want to base code on those strings. Introduce a boolean flag instead based on which you can execute code or not.

Consider this approach:

```
envConfig {
    env = local
    env = ${?ENVIRONMENT}

    local {
        executeCode = true
    }

    prod {
        executeCode = false
    }
}
```

Then in your code:

```
if (EnvConfig.getBoolean(executeCode)) {
        transaction {
            SchemaUtils.create(SomeTable)
            SchemaUtils.create(OtherTable)
        }
    }
```

**Comment by tuncererdogan** [comment]
@stolzem `EnvConfig.getString("env") `is not working and throwing a `KeyNotFoundException`. It seems be not loading in `initConfig` method. It might be better if an `env` method is added to achieve Rails like functionality. Please see [here](https://stackoverflow.com/questions/6476832/rails-how-do-i-check-developer-mode-or-production-mode-in-code).
